export class user
{
  id:any;
  empId:any;
  empName:any;
  empEmail:any;
  empDesignation:any;
  managerId:any;
  addr1:any;
  addr2:any;
  addr3:any;
  city:any;
  state:any;
  pincode:number;
  contactNumber:number;
  emergencyContact:number;
  bloodGroup:any;
  userType:any;
  departmentId:any;
  status:string
}
